language: java
sudo: false
jdk: oraclejdk8
install: mvn install
script: "mvn cobertura:cobertura"
cache:
    directories:
        - $HOME/.m2
after_success:
    - bash <(curl -s https://codecov.io/bash)
