sudo: required
dist: trusty
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
script: mvn clean install jacoco:report coveralls:report sonar:sonar
after_success:
    - bash <(curl -s https://codecov.io/bash)
cache:
    directories:
        - $HOME/.m2
