sudo: required
dist: trusty
language: java
jdk: oraclejdk8
after_success:
    - mvn clean test jacoco:report coveralls:report
cache:
    directories:
        - $HOME/.m2
after_success:
    - bash <(curl -s https://codecov.io/bash)
